//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedInfoDataEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedInfo
    {
        public int id { get; set; }
        public string category1 { get; set; }
        public string category2 { get; set; }
        public string category3 { get; set; }
        public string category4 { get; set; }
        public string category5 { get; set; }
        public string MedInfo1 { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> HitCounter { get; set; }
    }
}
